// examples/todo-ng-ts/src/app/footer/footer.component.ts
import { Component, Input, OnChanges, SimpleChanges } from '@angular/core'
import { Filter, Todo } from '../../state'
import { RemoveCompletedTodosAction, SetFilterAction } from '../../action'

@Component({
  selector: 'todo-footer',
  template: `
    <footer id="footer">
      <span id="todo-count"><strong>{{leftCount}}</strong>
          {{leftCount > 1 ? 'items' : 'item' }} left
      </span>
      <ul id="filters">
        <li>
          <a [class.selected]="filter == undefined || filter === 'ALL'"
             (click)="setFilter('ALL')">All</a>
        </li>
        <li>
          <a [class.selected]="filter === 'ACTIVE'"
             (click)="setFilter('ACTIVE')">Active</a>
        </li>
        <li>
          <a [class.selected]="filter === 'COMPLETED'"
             (click)="setFilter('COMPLETED')">Completed</a>
        </li>
      </ul>
      <button id="clear-completed" (click)="clearCompletedTodos()" *ngIf="completedCount > 0">Clear completed</button>
    </footer>
  `
})
export class TodoFooterComponent implements OnChanges {

  @Input()
  todos: Todo[]

  @Input()
  filter: Filter

  leftCount: number
  completedCount: number

  ngOnChanges(changes: SimpleChanges) {
    if (this.todos === undefined) return
    this.completedCount = this.todos.filter(item => item.completed).length
    this.leftCount = this.todos.length - this.completedCount
  }

  clearCompletedTodos() {
    new RemoveCompletedTodosAction().dispatch()
  }

  setFilter(filter: Filter) {
    new SetFilterAction(filter).dispatch()
  }

}

// examples/todo-react-es6-wo-decorators/src/app/footer.js
import Filter from './filter'
import React from 'react'
import { RemoveCompletedTodosAction } from '../action/todo-action'
import { State } from 'statex'

export default class Footer extends React.Component {

  subscriptions = []

  constructor(props) {
    super(props)
    this.state = {
      completedCount: 0,
      pendingCount: 0
    }
  }

  componentDidMount() {
    this.subscriptions.push(
      State.select(state => state.todos).subscribe(todos => {
        this.setState({
          completedCount: (todos || []).filter(todo => todo.completed).length,
          pendingCount: (todos || []).filter(todo => !todo.completed).length
        })
      })
    )
  }

  componentWillUnmount() {
    this.subscriptions.forEach(subscription => subscription.unsubscribe())
    this.subscriptions = []
  }

  clearCompleted() {
    new RemoveCompletedTodosAction().dispatch()
  }

  render() {
    const { pendingCount, completedCount } = this.state

    return <footer id="footer">
      {pendingCount != null &&
        <span id="todo-count"><strong>{pendingCount} </strong>
          {pendingCount > 1 ? 'items' : 'item'} left
        </span>
      }
      <Filter />
      {completedCount > 0 &&
        <button id="clear-completed"
          onClick={this.clearCompleted.bind(this)}>Clear completed</button>
      }
    </footer>
  }
}
