// examples/todo-react-es6/src/app/header.js
import { AddTodoAction, ToggleAllTodosAction } from '../action/todo-action'

import React from 'react'

// import { data, inject } from 'statex/react'

// export class Props {
//   // @data(state => (state.todos || []).reduce((checked, todo) => checked && todo.completed, true))
//   allChecked = false
// }

// @inject({
//   allChecked: state => (state.todos || []).reduce((checked, todo) => checked && todo.completed, true)
// })
export default class Header extends React.Component {

  constructor(props) {
    super(props)
    this.state = { todoText: '' }
  }

  handleSubmit(event) {
    event.preventDefault()
    if (!this.state.todoText) return
    new AddTodoAction({ text: this.state.todoText }).dispatch()
    this.setState({ todoText: '' })
  }

  handleChange(event) {
    this.setState({ todoText: event.target.value })
  }

  toggleAll(event) {
    new ToggleAllTodosAction(!event.target.checked).dispatch()
  }

  render() {
    const { allChecked } = this.props
    return (
      <header id="header">
        <h1>todos</h1>
        <form id="todo-form" onSubmit={this.handleSubmit.bind(this)}>
          <input id="new-todo" placeholder="What needs to be done?" name="todo" autoFocus
            value={this.state.todoText} onChange={this.handleChange.bind(this)} autoComplete="off" />
        </form>
        <input id="toggle-all" type="checkbox" checked={!allChecked} onChange={this.toggleAll.bind(this)} />
      </header>
    )
  }
}

// examples/todo-ng-ts-wo-decorators/src/app/header/header.component.ts
import { AddTodoAction } from '../../action'
import { Component } from '@angular/core'

@Component({
  selector: 'todo-header',
  template: `
    <header id="header">
      <h1>todos</h1>
      <form id="todo-form" (submit)="addTodo()">
        <input id="new-todo" placeholder="What needs to be done?" [(ngModel)]="todoText" name="todo" autoFocus autoComplete="off">
      </form>
    </header>
  `
})
export class TodoHeaderComponent {

  todoText: string

  addTodo() {
    if (this.todoText === undefined || this.todoText.trim() === '') {
      return
    }

    new AddTodoAction({
      text: this.todoText,
      completed: false
    }).dispatch()
      .then(() => this.todoText = '')
  }

}
